name: omnikingnile_tv
description: IPTV Player
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  better_player: ^4.1.0
  http: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/channels.json
