name: iptv_player
description: A simple IPTV player app
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  better_player: ^0.0.84
  flutter/services:
    path:.

flutter:
  uses-material-design: true
  
  assets:
    - assets/channels.json
